### ISSUE TITLE
Cocina map: translated language

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1216]
It should be able to round trip this xml as found on stage in druid:hc607hj7585
```xml
  <language>
    <languageTerm authority="iso639-2b" type="code">eng</languageTerm>
  </language>
  <language objectPart="translation">
    <languageTerm authority="iso639-2b" type="code">fre</languageTerm>
  </language>
```

currently it's omitting `objectPart`:
```xml
  <language>
    <languageTerm type="code" authority="iso639-2b">eng</languageTerm>
  </language>
  <language>
    <languageTerm type="code" authority="iso639-2b">fre</languageTerm>
  </language>
```

**Comment by ndushay** [comment]
I am nearly done implemented the full complement of language mappings.   for THIS ticket, there is an open question for @arcadiafalcone 

The example for language appliedTo shows a single value, which makes sense because it’s an attribute:  https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_language.txt#L127

But the cocina-model shows it as an array: https://github.com/sul-dlss/cocina-models/blob/master/lib/cocina/models/language.rb#L6   (see also https://github.com/sul-dlss/cocina-models/blob/master/openapi.yml#L183)

is cocina-models wrong? or is the example wrong?

**Comment by arcadiafalcone** [comment]
appliesTo should be an array - I'll update the example mapping.
