### ISSUE TITLE
Map originInfo eventType attribute

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1408]
For druid:cz548fn3478, expected:
```
<originInfo displayLabel="Place of creation" eventType="production">
```
but received:
```
<originInfo displayLabel="Place of creation">
```

Notice the missing eventType attribute.

**Comment by jmartin-sul** [comment]
is this the to_fedora half of #1379?

**Comment by justinlittman** [comment]
No, I think this is different. Specifically, it is adding `eventType="production"`.

**Comment by jmartin-sul** [comment]
ah yeah, sorry, i was conflating `dateOther` and `eventType` handling

**Comment by mjgiarlo** [comment]
@justinlittman I'm diving into originInfo stuff now. Just making sure this is still in your bailiwick. Yes?

**Comment by mjgiarlo** [comment]
Based on https://github.com/sul-dlss/dor-services-app/issues/1409#issuecomment-731410553, I believe this is done already.

**Comment by justinlittman** [comment]
Per @arcadiafalcone:
1. If an `<originInfo>` has a `<dateCreated>`, the event type should be `production`. The examples need to be updated: https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/176.
2. A

**Comment by mjgiarlo** [comment]
I started working on this, but I'm reluctant to dive in until the changes needed on the to_fedora and from_fedora sides are clearer in the spec: https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/176 

I'm going to suggest this issue is blocked by that work, but if :point_up: makes enough sense to you (the reader) to unblock this issue, have at it.

**Comment by justinlittman** [comment]
Can no longer reproduce, so fixed.
