### ISSUE TITLE
Fix "Multi-term topic subject with authority for terms" test

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1962]
In `subject_topic_spec.rb`.

**Comment by arcadiafalcone** [comment]
Note for reference: parts of subject structuredValues may have source values duplicating each other and/or the structuredValue, as needed, due to the complex interactions between source data for `subject` and its subelements. For other properties, the preferred model of entering the source statement as applying to the whole if it applies to all the parts is retained.
