### ISSUE TITLE
mods_normalization should remove all empty elements that have no attributes

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2034]
This should be "recursive" in that if an element only has similarly empty (and no attributes) sub elements, then the outermost empty element should be removed.

**Comment by justinlittman** [comment]
Can you give an example where this should be applied?

**Comment by arcadiafalcone** [comment]
Here's one: druid:nj954ht3332. Eventually we should strip out empty elements unless they meet the requirements listed in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_value_dependencies.txt, but I haven't created all of the mappings required yet. So `originInfo` in that example would also be dropped even though the `eventType` attribute has a value, because it's not one of the protected attributes that makes even valueless elements be retained.

**Comment by arcadiafalcone** [comment]
Another, non-APO example: druid:np850gx7608

**Comment by justinlittman** [comment]
Given the complexity of the rules, my approach has been to add specific delete empty normalization methods, rather than a generalize method. See, for example, https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/mods_normalizers/title_normalizer.rb#L28

So we can either continue with the current approach (slower, but probably less error prone) or try a generalize delete empty method.

**Comment by arcadiafalcone** [comment]
All attributes with no value should be dropped as well - is that covered here, or should it be ticketed elsewhere?

**Comment by ndushay** [comment]
I can take a stab at this.

**Comment by ndushay** [comment]
1.  empty attributes are already dropped, except in cases where we give them a default value in our normalization (e.g. languageTerm type, originInfo eventType)

2.  I believe I can write code to remove nested empty elements with no attributes ... for everything that doesn't get a default value.  I'm working on this now.

3.  For the special cases, e.g. eventType attribute on originInfo with no data ... we will need to do this on a per element basis.  So we'll probably need your help with the spec.  I see that https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_value_dependencies.txt has an explanation for the `<name>` element, but we already know there is a special case for `<originInfo>` with an `eventType` attribute ... etc.
