### ISSUE TITLE
Investigate connection issues to fedora 3

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor-services-app#2559]
Example error message:

```
Errno::EADDRNOTAVAIL: Failed to open TCP connection to sul-dor-prod.stanford.edu:443 (Cannot assign requested address - connect(2) for "sul-dor-prod.stanford.edu" port 443)
```

https://app.honeybadger.io/projects/50568/faults/78429477

The ongoing issues with losing connection to fedora 3 lead to incomplete data that often requires manual remediation. This will continue to be an issue while supporting fedora 3 as the data store behind dor-services-app.

see also https://github.com/sul-dlss/operations-tasks/issues/2432

**Comment by peetucket** [comment]
Ideas presuming the problem is caused by many simultaneous workers:

- reduce the number of common accessioning workers
- send media to the low priority lane
- adjust workers so that some do not pick up items from the slow lane

Other ideas:

- profiling on the jvm to see what might be triggering it
