### ISSUE TITLE
H2 mapping: Should Datacite property be Sponsor?

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2574]
... not Creator

https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb#L406

**Comment by arcadiafalcone** [comment]
No, because the cocina contributor has the "include in citation" note. In DataCite the categories are Creator (no additional role allowed) and Contributor (with a more specific role required). Anyone included in the citation maps to Creator for DataCite purposes regardless of the role they have in H2.
