### ISSUE TITLE
Map collection copyright property

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#2623]
`rightsMetadata/copyright` :left_right_arrow: `access/copyright`

Blocked by release of cocina-models 0.57.0

**Comment by jcoyne** [comment]
@andrewjbtw can you confirm that collections should be allowed to bear copyright statements.  Since a collection itself is not a creative work, this seems suspect to me.

**Comment by andrewjbtw** [comment]
It's an odd case, but I think we should still map copyright here because:

1. The metadata itself is copyrightable. Probably if people are really thinking of it this way, they would choose a different copyright for the metadata than for the objects but if they do they need the field.
2. From the public access standpoint the idea of a "collection object" is not clear. The collection display can stand in for a description of the collection overall, in which case having a copyright statement that is consistent with what's on the items themselves makes sense. In most cases, the collection will have the same statement as items because they all start from the same defaults.
3. We currently show copyright on collection purls. While "that's how we've always done it" doesn't necessarily mean we should continue to do that, in this case removing the copyright statement from the collection object would be a visible change (for new or republished purls) and I don't think we can make the call to change this right now.

**Comment by mjgiarlo** [comment]
Closed by #2632.
