### ISSUE TITLE
Remediate project Phoenix resource types and revert #2626

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#2630]
This error indicates these records can not be migrated to the next generation repository system.

**Comment by andrewjbtw** [comment]
I don't think this should be worked on until we determine what parts of Project Phoenix will be migrated at all. These objects were never migrated to the current generation repository and now we've downloaded most of these books in the Google Books redo and will likely discard the objects from the first attempt.

**Comment by andrewjbtw** [comment]
After we suspected that indexing problems contributed to more Fedora issues in late June, I decided to go ahead and remediate the Project Phoenix resource types because that was going to be faster than waiting until we've cleaned them up. 

I've completed the remediation and I think we can now revert #2626 to catch anything I might have missed.

**Comment by andrewjbtw** [comment]
The specific remediations I ran:

- changed resource types "file", "METS", or "metadata" to "object"
- changed the deprecated file attribute "deliver" to the currently used "publish"
- removed the deprecated <attr> tags
- removed the deprecated file attributes "dataType" and "format"
- lowercased the attribute names for the md5 and sha1 checksums
- changed all instances of "shelve" to "no" to reflect the reality that the files are not currently on Stacks

These items are still not versionable because they are not stored in Moab format and are not in prescat, but they should be valid cocina.
