### ISSUE TITLE
Type 'translated' added to multilingual title in roundtrip

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2658]
druid:bj242fk6517 
druid:bg217bb3003

**Comment by arcadiafalcone** [comment]
I changed https://github.com/sul-dlss/dor-services-app/blob/eff59cf9621167f466c79634e332c08e4cc7f627/app/services/cocina/to_fedora/descriptive/title.rb#L87
```
              else
                parallel_attrs[:type] = 'translated'
```
to
```
              elsif parallel_title.type == 'translated'   
                parallel_attrs[:type] = 'translated'
```
and roundtrip errors went from 154 to 37.

**Comment by jmartin-sul** [comment]
@arcadiafalcone, i tried this change, and i ran into some failures with existing unit tests...

if i make no other changes besides the `elsif parallel_title.type == 'translated'` you proposed, i get 4 total failures roundtripping back from cocina to MODS (and normalized MODS), all along the lines of (diff between expected/actual):
```xml
           <titleInfo usage=\"primary\" lang=\"fre\" altRepGroup=\"1\">\n
             <nonSort>Les</nonSort>\n
             <title>misérables</title>\n
           </titleInfo>\n
       -   <titleInfo type=\"translated\" lang=\"eng\" altRepGroup=\"1\">\n
       +   <titleInfo lang=\"eng\" altRepGroup=\"1\">\n
             <nonSort>The</nonSort>\n
             <title>wretched</title>\n
           </titleInfo>\n
         </mods>\n
```

if i add `type: 'translated'` as a sibling of `valueLanguage` in the expected cocina, i get fewer and different failures:  two failures in the same two shared examples, both of which are about the actual cocina not containing the expected `type: 'translated'` field.

should i adjust the mapping from fedora to cocina so that it includes `type: 'translated'` as a sibling of `valueLanguage`?  or should i do something else?

the specs in question from what's currently on `main` branch:
https://github.com/sul-dlss/dor-services-app/blob/2ac9d78e999eb9a738a8c887d0b6e2f0ce726730/spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb#L117-L160
https://github.com/sul-dlss/dor-services-app/blob/2ac9d78e999eb9a738a8c887d0b6e2f0ce726730/spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb#L162-L238

changes on my WIP branch:
https://github.com/sul-dlss/dor-services-app/blob/11571f54481991ea5d67230c8cf1c8fac12dfede/spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb#L145-L154
https://github.com/sul-dlss/dor-services-app/blob/11571f54481991ea5d67230c8cf1c8fac12dfede/spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb#L209-L233

**Comment by arcadiafalcone** [comment]
Yes, adding `type: 'translated'` is the preferred solution.
