### ISSUE TITLE
Implement updated abstract specs

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2728]
See #2727 

#2772 should be merged before working on this ticket.

**Comment by peetucket** [comment]
I'm having trouble getting all of the tests to pass as I make changes to the mappings to fix the now unskipped tests in #2727.

I'm wondering if this is because some of the tests are now inconsistent.  

For example, this existing test: https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/from_fedora/descriptive/related_resource_spec.rb#L136-L157 states that an abstract without a type goes to a note of type "summary":

```
       <relatedItem>
          <abstract>Additional data.</abstract>
        </relatedItem>
``` 

goes to 

```
        note: [
            {
              value: 'Additional data.',
              type: 'summary'
            }
          ]
```

But one of the tests in #2727 states that an abstract without a type goes to a note of type "abstract": https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb#L7-L23 :

```
      <abstract>This is an abstract.</abstract>
```
```

          note: [
            {
              value: 'This is an abstract.',
              type: 'abstract'
            }
          ]

```

Can I help understanding what to do?

**Comment by arcadiafalcone** [comment]
Type should be abstract as in the second example -- I must have missed relatedResource when I was doing the updates.

**Comment by peetucket** [comment]
ok, so I can update the existing test from `type: 'summary'` --> `type: 'abstract'`

If I stumble upon other cases like this, can I update those too?  Thanks

**Comment by arcadiafalcone** [comment]
Yes and yes.

**Comment by peetucket** [comment]
When you have a minute, can you look at the tests I updated in the draft PR I have?  https://github.com/sul-dlss/dor-services-app/pull/2836/files

I still have some more coding work to do, but since I had to touch a number of the existing tests to change "summary" to "abstract", I wanted to verify that I did it correctly.  

In addition to the coding I need to do to get all of the new unskipped tests to pass, I also can't this existing one to pass  after making my updates.  

Maybe you can verify it is correct: https://github.com/sul-dlss/dor-services-app/blob/377381f3f9782a2837bc168ed5d8528fc956c6ba/spec/services/cocina/mapping/descriptive/mods/note_spec.rb#L128-L154
I still can't get this one to pass, but maybe its because
