### ISSUE TITLE
Some actions can fail in save, but create resource anyway and returns a 500

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/dor-services-app#30]
I'm not sure what we should do about this, but some actions can fail on the `.save` method as the MD may be dirty and unable to reindex.

This will cause a `500` to be returned to a consumer, but  the information was updated anyways (and just fails on the `save`).

First noticed when using the `/release_tags` route: 

https://github.com/sul-dlss/dor-services-app/blob/master/lib/dor_services_app.rb#L171-L191

```
user [16/Sep/2016:12:20:03 -0700] "POST /v1/objects/druid:bb020sf5359/release_tags HT
TP/1.1" 400 59 0.6672
ERROR [2016-09-16 12:28:22] (27702)  :: #<NoMethodError: undefined method `match' for []:Array>
/path/shared/bundle/ruby/2.2.0/gems/stanford-mods-1.5.3/lib/stanford-mods/sea
rchworks.rb:19:in `block (2 levels) in sw_language_facet'
```

```
```

**Comment by LynnMcRae** [comment]
A recent slack conversation on this:

drh-stanford yeah a `.save` calls `update_index` which calls `to_solr`
  
lynnmcrae isn’t that 100% redundant since any save to Fedora will independently trigger a reindex … some one (some one thing?) wanted a synchronous reindex?)
 
mejackreed Seems like it...
  
lynnmcrae plus I thought the .save was needed to commit changes to the datastream. not sure why an implicit reindex is part of satisfying that need.
 
drh-stanford ActiveFedora is what calls the `update_index` method
 
mejackreed But I really don't know all of the global implications here.. That's why I raised the issue

lynnmcrae you can tell AF not to index as I recall, but could be totally wrong about that. I thought we had turned off (nearly?) all AF reindexes.
 
drh-stanford it could be that dor-services-app is not configured to do that — there’s an `ENABLE_SOLR_UPDATES` flag here — https://github.com/projecthydra/active_fedora/blob/6-7-stable/lib/active_fedora/persistence.rb#L132

**Comment by LynnMcRae** [comment]
I feel the forced reindex is a mistake here.  If it is directly tied into saving an update to Fedora, we should trust Fedora's background indexing queue to do its job. The caller can decide if a realtime reindex is called for via a separate call.

If it can't be eliminated, it should at least be considered secondary in cases like this and, lacking transactional rollback, not cause a 500 error since the actual work of the web service call succeeded.

**Comment by cbeer** [comment]
> lynnmcrae isn’t that 100% redundant since any save to Fedora will independently trigger a reindex

Functionally redundant, yes; however, if you were creating the object in a context where you want to immediately see the result (say, in Argo), it's pretty essential.

**Comment by jcoyne** [comment]
I think the correct solution here is to migrate off Fedora, so we don't need to index to solr after writing to the data store.  Solr is necessary for queries, which many data stores support without an external index.
