### ISSUE TITLE
Investigate Rails DB configuration to handle dropped connections

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3096]
Per suggestion from @julianmorley, investigate Rails DB configuration to properly handle dropped DB connections.

**Comment by julianmorley** [comment]
See c3p0 (Java) and Pear (PHP) for the kind of thing I'm talking about; either pre-try or re-try a connection on certain failure conditions. I have no idea what Ruby has in this space.

**Comment by jcoyne** [comment]
This is all handled by Rails https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L583-L588

**Comment by julianmorley** [comment]
My read of that code is that it only verifies on checkout, which wouldn't handle the issue I'm concerned about: a checked-out connection that is silently dropped on the other end.

**Comment by jcoyne** [comment]
@julianmorley checkouts are typically held only briefly, (e.g. the duration of a request). If you had an in use connection that dropped, I think it would be dangerous to reconnect and try to pick up where you left off because it may be more harmful to repeat operations on the data than to raise an error and have the caller figure it out.

**Comment by julianmorley** [comment]
@jcoyne If you made sure that each checkout is only used for 1 transaction, then I agree that's fine. But that's not guaranteed, right? You could have a checkout that's used for dozens, hundreds, thousands (I'm thinking batch processing that might happen in a repo here), and then you'd have a gap and no real way to write a good test case for it.

**Comment by justinlittman** [comment]
If my recollection is correct, c3p0 does testing at connection checkout, checkin, and/or while idle. I don't think it does any testing while the connection is checked out. (And I'm not sure what, other than failing and rolling back, could be done if a checked out connection is lost.)

**Comment by jcoyne** [comment]
We don't presently have any batch processing like that and we don't have anything like that planned for the near future.  It wouldn't really be a big problem if you were doing batch processing to run `conn.validate!` before each transaction.

**Comment by julianmorley** [comment]
c3p0 can be configured to test each connection before use; it was that feature that saved Coursework's butt back in the day (this is why I care so much about connection handling - we got burnt *a lot* by it as we were trying to make Coursework HA). 

There's a huge advantage to the connection pool adapter doing these checks so the app logic doesn't need to care. The app should never have to ask the pool adapter 'is this connection still good?'. The adapter should guarantee it; it's a killer feature of connection pooling and we need something like that to support hot DB failover. Currently we can only do 'cool' failover that requires config changes and app restarts.

The easiest way to make an app true HA is to plan for it from the start; in an ideal world I want to be able to fail over the DB in the background without the app logic even noticing. Low-level connection testing and reconnects at the connection pool level get us there.

**Comment by jcoyne** [comment]
@julianmorley The people at github and shopify are using the default rails connection pool.   I'm extremely skeptical that what works for them isn't going to work for our relatively tiny workloads.  We just want to be able to take down one node out of the pool at a time, the same way we can for argo. Let's not go hunting for problems where none exist.

**Comment by julianmorley** [comment]
@jcoyne do you know how they handle db failover? If you don't, it's academic. It's entirely possible to handle db failover with the default AR pool *if you code for it*. I'm asking you to code for it rather than assume it just works.

Taking one node out at a time works for certain failure conditions. It doesn't help at all for db failover. I'm told this is an important stack and you want 24x7x365, so that means planning for hot db failover.

c3p0 has an option where it does this for each attempt to use a checked-out connection: https://github.com/rails/rails/blob/411ffb464743829925d0d39d913df29f3431ac61/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L307
I can't find a similar option in AR setup, but I just might be missing it.

You could also just write your own connection wrapper that does the 'verify_and_reconnect' dance when a supposed-good checkout raises an exemption. This is probably the most efficient way to do it outside of the AR adapter, if the AR adapter doesn't do that.  

Or explicitly ensure that every transaction uses a new checkout. Or maybe do something else I haven't thought of.

The important thing is that you account for it; I really want to avoid having to restart the app if there's an underlying db failover event (or even just a db iptables reload or tcp timeout event which might disrupt existing presumed-good connections).

**Comment by jcoyne** [comment]
@julianmorley why don't you get the hardware set up and I'll show you how it works when you change the db master.  I feel like you are really stepping on our toes here. We know what is necessary, we understand the workload, we know the requirements.  People have been working on improving rails for 16 years, and they have a pretty good system for dealing with this.

**Comment by julianmorley** [comment]
@jcoyne right now, none of our postgres pairs support hot failover. We currently support cold failover via config change and app restart.

In the future, when we have an on-prem k8 cluster, we plan to implement postgres middleware that will support hot failover but that still invalidates all existing, open connections to the database. So the app needs to recover from that without requiring restarts / messing up the end user experience. 

How you do that is up to you, but you will need to do that if you want true HA. This isn't just for app-level issues; this is to enable us to failover, patch and reboot database servers without disrupting the app. We can't do that right now without a full stack shut down in a maintenance window. 

I am making a deal about this because I have had this *exact* conversation before with an entirely different group of Java developers, which is how we ended up using a specific config in c3p0. It was "Oh, Hibernate does that, don't worry!". And then it turned out that Hibernate didn't do that unless you actually asked it to. I'm getting the same vibe from you now about AR. AR *can* do it, if you design for it. I'm asking you to design for it. If you're convinced that no additional thought is necessary, then I will of course defer to your opinion and we can revisit this issue when we actually implement middleware that needs it.

**Comment by jcoyne** [comment]
What I'm trying to communicate is that rails does all the connection validation automatically at the beginning of every request.  There is nothing we need to do for a typical API application.   If we create a batch processing application, then we would need to ensure to have a block like:

```ruby
   ActiveRecord::Base.connection_pool.with_connection  do
      # code here
    end
```

around the place we want a valid connection, but this is already baked into the framework for http requests and background job processing.

**Comment by julianmorley** [comment]
Right. So if you know that:
- every time you ask for a connection from the pool, the pool explicitly checks the connection is live before handing it over
- every time the calling method wants to talk to the db it asks for a new connection, does one thing, then hands it back
Then I agree, we're good to go, AR will handle it fine.
