### ISSUE TITLE
Model / map resource node thumb attribute (content metadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3187]
Currently, some items have content metadata which includes resource nodes with a thumb attribute. Cocina does model the thumb attribute.

Does thumb need to be modeled in Cocina or can it be ignored? If it needs to be modeled, what are the current codebases that use it? When it is used, should it be limited to a single resource or can multiple resource have thumb="yes"? What type of objects/resources currently have thumb?

**Comment by jcoyne** [comment]
I believe this is used by PURL here:

https://github.com/sul-dlss/purl/blob/6dfed5ebcf95c5a5d860f5ad6fae8aa636b4cf26/app/models/public_xml.rb#L34-L36

This node is constructed in the public xml via DSA here:
https://github.com/sul-dlss/dor-services-app/blob/b155403e85015003dafb6e34a6e196003cba4866/app/services/publish/public_xml_service.rb#L33-L34

And the ThumbnailService uses the thumb attribute as a hint:

https://github.com/sul-dlss/dor-services-app/blob/main/app/services/thumbnail_service.rb#L11-L13

Interestingly it looks like `@type='thumb'` can be used if the resource is not `@type="page" or @type="image"`

**Comment by andrewjbtw** [comment]
Could I have a report of items that use this? I've never seen it in action.

**Comment by justinlittman** [comment]
Initial action for this ticket: Write a report to find items that have resource nodes with a thumb attribute in content metadata.

**Comment by lwrubel** [comment]
Report with 10 druids ([example](https://argo.stanford.edu/view/druid:hj097bm8879)) that have a thumb attribute on a resource node in contentMetadata.

[content-resource-thumb.csv](https://github.com/sul-dlss/dor-services-app/files/7907645/content-resource-thumb.csv)

**Comment by andrewjbtw** [comment]
I'm surprised that there are only 10 items with the thumb attribute. I looked at each of them. 8 of them were cases where the thumb attribute should not have been used at all - all media objects - and I've removed it from all of them. That leaves behind two druids where the thumb seems to have been marked in the way it was intended, to refer to pages in a book or multi-image object:

https://argo.stanford.edu/view/druid:wp146tq7625
https://argo.stanford.edu/view/druid:hj097bm8879

In both cases, the thumb attribute has been applied to a specific resource within the object that is not the first file in the sequence. That is, instead of marking the cover as a thumb, an internal pages has been marked as a thumb. Theoretically, this means that the embed viewer should use the specified "thumb" resource as the thumbnail in the display. But it looks like the viewer is showing the first image instead.

This raises the question of whether setting custom thumbnails using the "thumb" attribute has ever been supported.

**Comment by jcoyne** [comment]
@lwrubel was the 10 objects you found a sample or the full result set?

**Comment by lwrubel** [comment]
That was the full result set--here is the report code: https://github.com/sul-dlss/dor-services-app/blob/main/bin/reports/report-content-thumb

**Comment by justinlittman** [comment]
I just re-ran the report and 0 objects with `thumb` so closing this ticket.
