### ISSUE TITLE
[dor-services-app/prod] Cocina::Models::ValidationError: "person" isn't part of the enum in #/components/schemas/AccessRoleMember/properties/type

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3225]
## Backtrace

    line 50 of [PROJECT_ROOT]/app/services/cocina/mapper.rb: build
    line 28 of [PROJECT_ROOT]/app/services/cocina/mapper.rb: build
    line 57 of [PROJECT_ROOT]/app/controllers/objects_controller.rb: show

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/78631512)

**Comment by andrewjbtw** [comment]
It looks like this error is preventing APOs that use sunetId-based roles from being indexed correctly.

This object uses the Revs APO, but the APO field in the display is only showing the druid: https://argo.stanford.edu/view/druid:yv317mh3509

The Revs APO shows the banner warning that it can't be represented in Cocina, which means only admins can load the APO: https://argo.stanford.edu/view/druid:qv648vd4392

The issue will probably also affect registration since users need to choose an APO at that point.
