### ISSUE TITLE
clarify HB alert for "Invalid resource type"

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3232]
From druid:zn580kw6428

## Backtrace

    line 54 of [PROJECT_ROOT]/app/services/cocina/from_fedora/file_sets.rb: resource_type
    line 30 of [PROJECT_ROOT]/app/services/cocina/from_fedora/file_sets.rb: block in build
    line 24 of [PROJECT_ROOT]/app/services/cocina/from_fedora/file_sets.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/79080969)

**Comment by jmartin-sul** [comment]
wasn't sure what "done" was supposed to look like, discussed w/ justin after standup.  we think that andrew fixed this particular example (it does have a `type` attribute on the `resource` element now, and was updated 2 days ago).  it was decided that we'll tweak the warning in this message so that it's like our other honeybadger bad data warnings (which we think was a honeybadger tag to that effect, but i'll double-check that).
