### ISSUE TITLE
Normalize twentyPctVisibility* (embargo metadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3285]
From druid:cb931sc6206:
```
Original XML for embargoMetadata:
<?xml version="1.0"?>
<embargoMetadata>
  <status/>
  <releaseDate/>
  <releaseAccess/>
  <twentyPctVisibilityStatus>released</twentyPctVisibilityStatus>
  <twentyPctVisibilityReleaseDate>2019-06-03T07:00:00Z</twentyPctVisibilityReleaseDate>
</embargoMetadata>


Normalized original XML for embargoMetadata:
<?xml version="1.0" encoding="UTF-8"?>
<embargoMetadata>
  <twentyPctVisibilityStatus>released</twentyPctVisibilityStatus>
  <twentyPctVisibilityReleaseDate>2019-06-03T07:00:00Z</twentyPctVisibilityReleaseDate>
</embargoMetadata>


Roundtripped XML for embargoMetadata:
<?xml version="1.0"?>
```

When value of `<twentyPctVisibilityStatus>` is "released", `<twentyPctVisibilityStatus>` and `,<twentyPctVisibilityReleaseDate>` should be removed in normalization.

**Comment by jcoyne** [comment]
@justinlittman I don't belive we have any twentyPctVisibility that is not released at this point.

**Comment by edsu** [comment]
@justinlittman @jcoyne it [looks like](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/normalizers/embargo_normalizer.rb#L37-L42) the current logic only modifies embargo metadata when `<status>released</status>` is present?

Will it be ok if this new normalization only happens when that element is present too? [Here](https://github.com/sul-dlss/dor-services-app/blob/t3285-normalize-twentypct/app/services/cocina/normalizers/embargo_normalizer.rb) is my current implementation.
