### ISSUE TITLE
Map DOI (identity metadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3286]
For example, druid:cf448xg0843"
```
<?xml version="1.0"?>
<identityMetadata>
  <doi>10.25740/cf448xg0843</doi>
</identityMetadata>
```

This should be mapped to identification > doi.

**Comment by justinlittman** [comment]
I'm not sure. Here's the roundtrip report:
```
Diff for identification:
 {
   "catalogLinks": [
 
   ],
-  "doi": "10.25740/cf448xg0843",
   "sourceId": "hydrus:object-4906"
 }


Difference found for identityMetadata
Diff for identityMetadata:
-<?xml version="1.0" encoding="UTF-8"?>
+<?xml version="1.0"?>
 <identityMetadata>
   <sourceId source="hydrus">object-4906</sourceId>
   <objectId>druid:cf448xg0843</objectId>
   <objectCreator>DOR</objectCreator>
   <objectType>item</objectType>
-  <objectLabel>Limitations of the Intellectual Borders created by the Human Rights Field: A Fractal Exploration of Drummond in Chiriguaná, Colombia</objectLabel>
-  <doi>10.25740/cf448xg0843</doi>
+  <objectLabel>Limitations of the Intellectual Borders created by the Human Rights Field: A Fractal Exploration of Drummond in Chiriguan&#xE1;, Colombia</objectLabel>
 </identityMetadata>
 
+

Original XML for identityMetadata:
<?xml version="1.0"?>
<identityMetadata>
  <sourceId source="hydrus">object-4906</sourceId>
  <objectId>druid:cf448xg0843</objectId>
  <objectCreator>DOR</objectCreator>
  <objectType>item</objectType>
  <objectLabel>Limitations of the Intellectual Borders created by the Human Rights Field: A Fractal Exploration of Drummond in Chiriguan&#xE1;, Colombia</objectLabel>
  <doi>10.25740/cf448xg0843</doi>
</identityMetadata>


Normalized original XML for identityMetadata:
<?xml version="1.0" encoding="UTF-8"?>
<identityMetadata>
  <sourceId source="hydrus">object-4906</sourceId>
  <objectId>druid:cf448xg0843</objectId>
  <objectCreator>DOR</objectCreator>
  <objectType>item</objectType>
  <objectLabel>Limitations of the Intellectual Borders created by the Human Rights Field: A Fractal Exploration of Drummond in Chiriguaná, Colombia</objectLabel>
  <doi>10.25740/cf448xg0843</doi>
</identityMetadata>


Roundtripped XML for identityMetadata:
<?xml version="1.0"?>
<identityMetadata>
  <sourceId source="hydrus">object-4906</sourceId>
  <objectId>druid:cf448xg0843</objectId>
  <objectCreator>DOR</objectCreator>
  <objectType>item</objectType>
  <objectLabel>Limitations of the Intellectual Borders created by the Human Rights Field: A Fractal Exploration of Drummond in Chiriguan&#xE1;, Colombia</objectLabel>
</identityMetadata>
```

Can you figure out what is going on?

**Comment by lwrubel** [comment]
I added a couple of specs to evaluate roundtripping, and the DOI is successfully retained in the roundtripped XML when tests are run.

In pairing with @mjgiarlo, we figured out that there is an issue with the `validate-cocina-roundtrip` script, specifically, the assign_doi argument not being passed to Cocina::ObjectCreator.trial_create. This leads to the DOI not being available [to be added to the normalized roundtripped XML](https://github.com/sul-dlss/dor-services-app/blob/7692f3df5ab896f47936ce053c32174711dff4c6/bin/validate-cocina-roundtrip#L137) that the validate script is creating for comparison. 

See the draft PR for what the changes so far are. However, the roundtripping is still not successful because of `config/settings.yml`'s datacite prefix which is different in production. The DOI prefix gets change from 10.25740 to 10.80343. 

@justinlittman and @ndushay: should we normalize the DOI prefix to handle that prefix mismatch? Or handle any of the possible changes above in a different way?

**Comment by justinlittman** [comment]
Nice find! Normalization sounds like the correct approach to me.

**Comment by lwrubel** [comment]
I'm seeing that the roundtripped cocina will also need normalizing to change the prefix back to 80343. Does that sound correct? Seems like a rare case to need to do that so wanted to check in about that.

**Comment by justinlittman** [comment]
As long as the roundtripping works out in the end.

**Comment by lwrubel** [comment]
I realized that setting assign_doi: true in trial_create was leading to a DOI being put on all records when the validate-cocina-roundtrip script is run, whether or not they originally had a DOI. So need to address that still.
