### ISSUE TITLE
Map/normalize group (roleMetadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3319]
From druid:cj081cq3344:

```
<?xml version="1.0"?>
<roleMetadata>
  <role type="hydrus-collection-manager">
    <person>
      <identifier type="sunetid">dhartwig</identifier>
      <name/>
    </person>
    <person>
      <identifier type="sunetid">jschne</identifier>
      <name/>
    </person>
    <person>
      <identifier type="sunetid">hahn1</identifier>
      <name/>
    </person>
  </role>
  <role type="hydrus-collection-depositor">
    <person>
      <identifier type="sunetid">dhartwig</identifier>
      <name/>
    </person>
  </role>
  <role type="dor-apo-manager">
    <group>
      <identifier type="workgroup">sdr:psm-staff</identifier>
    </group>
    <group>
      <identifier type="workgroup">sdr:developer</identifier>
    </group>
    <group>
      <identifier type="workgroup">sdr:metadata-staff</identifier>
    </group>
  </role>
  <group>
    <identifier type="workgroup">sdr:metadata-staff</identifier>
  </group>
</roleMetadata>
```

Can the `<group>` that is not under a role be removed in normalization? Or does it need to be mapped?

**Comment by andrewjbtw** [comment]
At one point the only way to update `roleMetadata` was to type the changes straight into the XML. Given that, I think we should assume any workgroup that's in the `roleMetadata` is supposed to be under a role. If the workgroup is also already nested under a role (as in the example above where sdr:metadata-staff appears twice) it can be normalized out since moving it to the role would be redundant.

If the workgroup is not one of the groups listed under a role, then I think I need to look at it. Could I have a report of items where the workgroup appears only in a `<group>` that is not under a role?

**Comment by justinlittman** [comment]
Initial action for this ticket: Create a report report of items where the workgroup appears only in a <group> that is not under a role.

**Comment by ndushay** [comment]
We will need to do this for APO objects as well as Collection and DRO.

**Comment by andrewjbtw** [comment]
Only APOs have roles.

**Comment by aaron-collier** [comment]
FYI - there are about 270 of these, all in the "SDR Graveyard" https://argo.stanford.edu/view/druid:kg712km1576 APO.

**Comment by justinlittman** [comment]
Action for this ticket: In normalization, remove `<group>` that are a child of `<roleMetadata>`, not `<role>`.

**Comment by ndushay** [comment]
Please make sure to test this with the druids mentioned above and with druids.apo.txt.

**Comment by aaron-collier** [comment]
What is `druids.apo.txt`?

**Comment by aaron-collier** [comment]
I found it in jlits path. We might want to add this to the readme if it's part of the process...
