### ISSUE TITLE
Rewrite content metadata in PublicXmlService to map from a cocina item

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3329]
Currently, content metadata that is including in the public XML is derived from a Fedora object. It should be re-written to derive it from a Cocina object. The public XML should remain unchanged.

You should be able to re-use the [ContentMetadataGenerator](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/content_metadata_generator.rb) for this.

[See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_xml_service.rb#L24](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_xml_service.rb#L25)

refs https://github.com/sul-dlss/dor-services-app/issues/3098

**Comment by andrewjbtw** [comment]
I'm seeing a change in the `<resource "id">` attribute in the public XML after a republish. I'm not sure if that's intended.

Example from https://argo-stage.stanford.edu/view/druid:fm539yc9854

Before:
```
    <resource id="cocina-fileSet-5b074b49-c431-4704-84b4-c7d61505bdc9" sequence="1" type="image">
```
After:
```
    <resource id="cocina-fileSet-fm539yc9854/5b074b49-c431-4704-84b4-c7d61505bdc9" sequence="1" type="image">
```

In the before, the `id` is `cocina-fileSet-` followed by a uuid, in the after it's `cocina-fileSet-` followed by the druid, followed by `/`, followed by the uuid. I know we're doing some filtering of the full Cocina URI so that it's compatible with Access applications, but I don't know what exactly is supposed to be filtered out besides the `http` prefix.

**Comment by justinlittman** [comment]
This is intentional. It came from the need to keep our file / fileset identifiers stable (instead of changing them up every mapping).

**Comment by andrewjbtw** [comment]
Testing on items:

Except for the identifiers, this looks good. We are publishing the "publish/shelve/preserve" settings where we didn't before, but there doesn't seem to be any harm in doing so. We're also publishing the checksums, which should satisfy the request in https://github.com/sul-dlss/dor-services-app/issues/3077

Testing on collections:

Collections don't have contentMetadata/structural metadata but I checked publishing them anyway. They're throwing an error, apparently because they don't have structural metadata: https://github.com/sul-dlss/dor-services-app/issues/3077
