### ISSUE TITLE
Rewrite rights metadata in PublicXmlService to map from a cocina item

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3330]
Currently, rights metadata that is including in the public XML is derived from a Fedora object. It should be re-written to derive it from a Cocina object. The public XML should remain unchanged.

See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_xml_service.rb#L26

refs https://github.com/sul-dlss/dor-services-app/issues/3098

**Comment by andrewjbtw** [comment]
Not sure if the scope of this ticket covers:

- what's included in the `<rightsMetadata>` Fedora datastream

OR

- what's included in the `<rightsMetadata>` block in the public XML

These are not identical. The license, copyright, and useAndReproduction statements from the datastream get inserted into the public XML MODS. That also needs to be accounted for, either under this issue or another one.

**Comment by andrewjbtw** [comment]
I've tested this on stage. I see two issues, one minor, the other with more serious consequences.

**Minor issue**: public XML includes empty elements

When there is no license, use and reproduction statement, or copyright statement, the publish is inserting empty elements into the public XML. 

Example: https://argo-stage.stanford.edu/view/bg081jv6633

The rightsMetadata datastream for this objects consists only of `access` nodes:

```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <none/>
    </machine>
  </access>
</rightsMetadata>
```

The public XML includes elements under `use` but they are all empty:
```xml
 <rightsMetadata>
    <access type="discover">
      <machine>
        <world/>
      </machine>
    </access>
    <access type="read">
      <machine>
        <none/>
      </machine>
    </access>
    <use>
      <human type="useAndReproduction"/>
      <license/>
    </use>
    <copyright>
      <human/>
    </copyright>
  </rightsMetadata>
```
The rightsMetadata in the public XML should not include the empty elements, though as far as I know this does not cause any issues.

**Major issue**: file-level rights are being stripped out

This issue is more serious because it can lead to files being either more or less restricted than they should be. The tricky thing here is that file-level rights are in structural metadata in Cocina, but in rightsMetadata in Fedora. So the publish code needs to pull the file rights out of the structural section and insert them into the rightsMetadata public XML.

Example: https://argo-stage.stanford.edu/view/druid:wf816pb3072

One of the files in this druid has "world (no-download)" rights. The remaining files have world rights, as does the object itself.

In Cocina, the rights are represented as:

object-level
(in the `access` section):
```
 "access": {
    "access": "world",
    "download": "world"
  },
```
file-level 
(in the `structural` section, showing only the file with the "world (no-download)" rights):

```
"structural": {
    "contains": [ ...
      {
        "structural": {
          "contains": [ ...
            {
              "label": "placeholder.jp2",
              "filename": "placeholder.jp2",
              "access": {
                "access": "world",
                "download": "none"
```
In Fedora, the rights are all represented together in the rightsMetadata:

```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <file>placeholder.jp2</file>
    <machine>
      <world rule="no-download"/>
    </machine>
  </access>
</rightsMetadata>
```
The Access systems expect the Fedora representation to include the file-level rights. What's happening now is that the file-level rights are being stripped out, which in this case would result in the `placeholder.jp2` file being treated as "world" instead of "world (no-download)".

This is the before and after I got when republishing the purl for this druid.

Before:
```xml
<publicObject id="druid:wf816pb3072" published="2022-02-22T22:05:41Z" publishVersion="dor-services/9.6.2">
  <rightsMetadata>
    <access type="discover">
      <machine>
        <world/>
      </machine>
    </access>
    <access type="read">
      <machine>
        <world/>
      </machine>
    </access>
    <access type="read">
      <file>placeholder.jp2</file>
      <machine>
        <world rule="no-download"/>
      </machine>
    </access>
  </rightsMetadata>
```
After:
```xml
<publicObject id="druid:wf816pb3072" published="2022-03-02T00:41:03Z" publishVersion="dor-services/9.6.2">
  <rightsMetadata>
    <access type="discover">
      <machine>
        <world/>
      </machine>
    </access>
    <access type="read">
      <machine>
        <world/>
      </machine>
    </access>
    <use>
      <human type="useAndReproduction"/>
      <license/>
    </use>
    <copyright>
      <human/>
    </copyright>
  </rightsMetadata>
```

When writing file-level rights to public rightsMetadata, it's not necessary to insert the rights for every single file, just for files where the rights are exceptions to the object-level rights. That's why the original public XML does not enumerate the rights to the two "world" files.
