### ISSUE TITLE
Remediate dark objects with publish="yes" or shelve="yes"

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3605]
83,415 objects in this state

[content-dark-rights-publish-shelve.csv](https://github.com/sul-dlss/dor-services-app/files/8145591/content-dark-rights-publish-shelve.csv)

**Comment by andrewjbtw** [comment]
Fun times.

**Comment by andrewjbtw** [comment]
I tagged all 83,415 objects in Argo to see what we're dealing with. 
https://argo.stanford.edu/catalog?f%5Btag_ssim%5D%5B%5D=remediation+%3A+shelve-publish-rights

For some items changing the publish/shelve to "no" is going to be the right thing to do but for others the rights may need to be changed. Almost 60,000 items on this list are from just two APOs.

**Comment by andrewjbtw** [comment]
I believe these are now all fixed but since there were so many we should re-run the report to check.

The remediation was:

- set web archive items to citation in keeping with the current settings
- check if files set to "preserve=no" are JP2 images made from JPGs or TIFFs
  - once "publish=no" and "shelve=no" these files will not be saved anywhere
  - JP2 derivatives do not need to be saved, but JP2 source files do need to be in preservation
  - only 3 files (1 PDF and 2 JP2s) did not have matching TIFFs or JPGs (based on filename pattern)
- reaccession the 3 druids with non-preserved files
- set all files in all remaining druids to "publish=no", "shelve=no"

This remediation will result in many JP2 files have "publish=no, shelve=no, preserve=no", which means that the files with those settings won't be saved anywhere the next time accessionWF is run. That looks odd but is the expected behavior when rights are deliberately changed to dark.

**Comment by justinlittman** [comment]
I re-ran the report and it was empty.
