### ISSUE TITLE
Examine roundtripping error with default object rights for druid:tv773sn2276

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3715]
```
<access type="read">
    <machine>
      <location rule="no-download">spec</location>
    </machine>
  </access>
```

**Comment by andrewjbtw** [comment]
What's wrong with those rights?

**Comment by justinlittman** [comment]
```
{
   "accessTemplate": {
     "view": "location-based",
     "copyright": "All rights reserved.",
-    "download": "none",
+    "download": "location-based",
     "location": "spec",
     "useAndReproductionStatement": "While Special Collections is the owner of the physical and digital items, permission to examine collection materials is not an authorization to publish. These materials are made available for use in research, teaching, and private study. Any transmission or reproduction beyond that allowed by fair use requires permission from the owners of rights, heir(s) or assigns. See: http://library.stanford.edu/spc/using-collections/permission-publish. Access Condition: Content is available for access via the Special Collections Reading Room."
   },
```

**Comment by justinlittman** [comment]
Initial work: Investigate the cause of the mapping problem.

**Comment by andrewjbtw** [comment]
It's valid as XML but doesn't map to a value in the (current) rights menu, which I assume is where you're seeing `loc:spec-nd`. That rights menu has never captured all valid rights settings and should not be taken as a measure of validity. In the Fedora model only the XML is the authority on what's valid and this combination is both valid and currently being enforced on the Purl.

**Comment by andrewjbtw** [comment]
This ticket is to make a menu that can handle this value in the UI: https://github.com/sul-dlss/argo/issues/2967

**Comment by justinlittman** [comment]
To clarify: in the underlying rights datastream code in dor-services, `loc:spec-nd` isn't handled. (That is, it isn't just missing from the UI.) If the new rights menu allows creating this, it will cause problems when saving to Fedora.

cc @jcoyne

**Comment by andrewjbtw** [comment]
I guess I'm still not understanding where the issue is. I just made this item "location (spec): no-download" by editing the datastream: https://argo-stage.stanford.edu/view/druid:bv179bv4340 

Location-based no-download rights have been on the list of valid rights since last year: https://docs.google.com/spreadsheets/d/1BesuZ3iqouFMaur79A61Uq4ewsHQc4I0w1fRBQoYugk/edit#gid=998877965

My collection of valid rights examples includes these rights: https://argo-stage.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Aft979jr4257

We also index these rights correctly in the facets, search results, and show page, and they work on the Purl. 

If these cases aren't supported somewhere in the code and we're only finding out now, then that means there was a problem in our process somewhere.
