### ISSUE TITLE
Report on invalid w3cdtf dates in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3796]
This report should identify any date value (dateCreated, dateIssued, dateCaptured, dateValid, dateModified, copyrightDate, dateOther) that has an encoding attribute with the value w3cdtf but does not match a valid w3cdtf pattern. The desired output is the druid and the date value.

Valid w3cdtf encoding
   Year:
      YYYY (eg 1997)
   Year and month:
      YYYY-MM (eg 1997-07)
   Complete date:
      YYYY-MM-DD (eg 1997-07-16)
   Complete date plus hours and minutes:
      YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
   Complete date plus hours, minutes and seconds:
      YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
   Complete date plus hours, minutes, seconds and a decimal fraction of a
second
      YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)

**Comment by lwrubel** [comment]
@arcadiafalcone, are any particular collections or projects where I might easily find examples of records that have the encoding="w3cdtf" for dates?

**Comment by arcadiafalcone** [comment]
Here's one: https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Akx532cb7981

**Comment by lwrubel** [comment]
Thanks! Looking like I can find many examples for dateCreated in the Stanford University Libraries -University Archives collection.

**Comment by arcadiafalcone** [comment]
Yep - in general if it's an AD date and doesn't come from MARC, H2, or web archives, it will probably be w3cdtf.

**Comment by arcadiafalcone** [comment]
Thanks - those should be edtf instead of w3cdtf anyway, so it's good to know.

**Comment by arcadiafalcone** [comment]
If it's not too late to include the APO as well as the item druid in the output, that would be helpful. Thanks!

**Comment by lwrubel** [comment]
The set of druids I've run the report on has all druids, so it already includes APOs. Is it a problem if they are all in one report? 

The report columns are the standard ones in the reports we've been running: druid,apo,catkey,message. In this case the message is the invalid dates, separated by semicolons. 

There are 156,048 druids with invalid dates. The vast majority are dates of the format YYYY-MM-DDTHH:MM:SS (e.g. 2008-07-10T18:13:24) so are invalid because there's no UTC offset. 

[desc-w3cdtf.csv](https://github.com/sul-dlss/dor-services-app/files/8428002/desc-w3cdtf.csv)

**Comment by arcadiafalcone** [comment]
OK, good. In the roundtrip validation report you have to specifically flag for the object's APO to be included in the results, which is why I wanted to call it out in particular. But if it's already included all is well.
