### ISSUE TITLE
Require parameters for versions create endpoint

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3906]
Currently, a number of parameters are permitted: (https://github.com/sul-dlss/dor-services-app/blob/main/app/controllers/versions_controller.rb#L71-L78)

The description (string)  and significance (String enum:  'major', 'minor', 'patch') parameters should be required.

**Comment by justinlittman** [comment]
Note, to be consistent with other controllers, this should be done with `params.require` rather than openapi.

**Comment by jcoyne** [comment]
@justinlittman openapi also serves as documentation, so is it possible we put it there as well?

**Comment by ndushay** [comment]
@jcoyne are there examples of required POST parameters in our openapi.yml?

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor-services-app/blob/main/openapi.yml#L206-L240

**Comment by ndushay** [comment]
The example you give indicates the parameters are in the query ... but they are in the posted request, so ... we prefer having documentation in openapi.yml that is incorrect as to "where" the parameter is passed, rather than ... whatever would be the correct way to indicate the required POST params?
