### ISSUE TITLE
Export data from Fedora

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3924]
After Fedora has been decommissioned, export all data.

**Comment by andrewjbtw** [comment]
I'd like to review the points for and against the two methods: the Fedora archive format or the migration to OCFL. I spent some time looking at the OCFL representation and both seem like viable methods.

As I recall, the Fedora archive format is hard to generate without causing problems with Fedora itself. The OCFL method doesn't seem to have that problem but the number of files and folders generated is going to be enormous. Every datastream edit is apparently its own OCFL version and we have druids in the migrate environment with dozens of versions, a few with more than 100. So that will mean a lot of small files spread out on the filesystem.

**Comment by edsu** [comment]
I think we resolved to exporting the FOXML rather than the (disk intensive) OCFL, since @andrewjbtw is already familiar with using it, and it will use less disk space, and be more manageable for what we need it for. The idea would be to run [archive-fedora](https://github.com/sul-dlss/dor-services-app/blob/main/bin/archive-fedora) after it is no longer being actively used by other services.

**Comment by peetucket** [comment]
- Waiting for Fedora to get disconnected (week of May 9)
- Need to request a file system from Ops to decide where to put the exported content.
