### ISSUE TITLE
Report on invalid W3CDTF dates in Cocina description

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4073]
This is to check remediation progress for invalid W3CDTF dates. For valid date patterns see #3848.

Desired output: druid, collection druid, catkey, date value(s).

Check for values in description..date..value with description..date.encoding.code w3cdtf.

**Comment by ndushay** [comment]
How one might do this:

https://www.postgresql.org/docs/current/functions-json.html

```
dor_services=# select external_identifier from dros where jsonb_path_query_first(description, 'strict $.**.parallelContributor.size() > 0') = 'true' limit 1;
 external_identifier
---------------------
(0 rows)
```

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/54882009-8917-412d-8b4b-93b55e3344af
)

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/a9cab2f2-46e5-463a-a192-9471e704cac4)

**Comment by justinlittman** [comment]
Alternatively, one might write a report harness that iterates over each item and tests each item in code (presumably with parallelization). This is similar to the previous report tooling, but gets Cocina items from the DB instead of Fedora items from the cache.

I'm not sure it will be possible to express something like date validation in a SQL statement.

**Comment by ndushay** [comment]
please include sourceids and look at the PR for #4072.

**Comment by mjgiarlo** [comment]
Chatted with Arcadia and she only needs the catkey, not source ID(s).

**Comment by mjgiarlo** [comment]
[bad_w3cdtf_report.csv](https://github.com/sul-dlss/dor-services-app/files/8874554/bad_w3cdtf_report.csv)

@arcadiafalcone here's the W3CDTF report. it's a bit of a doozy.
