### ISSUE TITLE
Test for side effects of latest displayName mapping

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4075]
In old PR #3748, there was a mapping for displayName that met Arcadia's specs, but seemed to negatively impact roundtrip testing with Fedora 3.

We're now out of Fedora 3 (yay!), and we moved the mapping code to sul-dlss/cocina-models, and PR sul-dlss/cocina-models/pull/480 re-implemented the above PR.

HOWEVER, I forgot to ask for confirmation that there were no side effects to this mapping.

Our whole way of checking for this used to be code we ran on sdr-deploy VM to do roundtrip validation against a fedora cache.  

To do these checks in our postgres based world ... I'm not sure how we would go about this exactly.  Maybe @justinlittman has some ideas?  (grab the json, or json fragments, for n00,000 objects from postgres and run it through a similar roundtrip validation?)

For reference, the PRs removing the roundtrip validation code (using Fedora 3) are:  #3897, #4011

**Comment by justinlittman** [comment]
Previously we cared about roundtrip mapping because we were doing huge amounts of mapping as part of persistence of every object and for migration. Now that we are no longer doing all of this mapping, what is the scenarios that we care about roundtrip mapping? This will help determine what we need to test and how much effort to invest. Maybe for the current scenarios, unit tests are good enough?

**Comment by jcoyne** [comment]
@ndushay Round trip validation is no longer something we no longer want to do because Cocina is more expressive than MODS.  We had to do this for Fedora 3 because, MODS was the serialization for persistence, but we no longer have that constraint.

**Comment by ndushay** [comment]
If you look at PR #3748 conversation, you will see that the last mapping I implemented BROKE a bunch of records in the roundtrip validation.  I no longer recall if @arcadiafalcone  looked at the "broken" records and determined that the records in question all boiled down to some specific MODS that we no longer need care about replicating ... or if there was still analysis to be done.  

Basically, I think I did 2, and maybe 3 separate implementations of displayName because implementing Arcadia's specs surfaced problem cases that required her to rework the algorithm she wanted once or twice.   What I'm trying to express here is essentially:  

"Is @arcadiafalcone confident that the mapping from sul-dlss/cocina-models/pull/480 will produce the desired MODS for the breadth of our cocina representations ... and is she convinced we have the correct cocina representations for displayName for all our current records in production ... based on the problems encountered in PR #3748 roundtrip stats."

**Comment by arcadiafalcone** [comment]
The records in #3748 broke because of a data error that has now been fixed.

If the tests in https://github.com/sul-dlss/cocina-models/pull/480 are passing, then I am confident that it will produce the correct MODS.

Production records do contain incorrect cocina representations for display name. I will need a report of contributors with display names in order to identify and remediate these records.
