### ISSUE TITLE
Remediate Cocina with barcode only, no catkey

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4327]
FOLIO HRIDs will be based on Symphony catkeys, not barcodes, so the catkeys must be added to the Cocina in order to also add the HRID.
 @andrewjbtw identified 581 such objects: ~~https://stanford.enterprise.slack.com/files/WLPPXB54G/F04LRQRRQGP/only-barcodes-with-title.csv~~  (arcadia supplied report below in a comment).

The action for this ticket is to take Arcadia's list below and determine the ckeys for each barcode.  Output of druid, barcode, catkey would be helpful;  ask Arcadia if she wants more than that.   If it gets more complicated, you might be able to leverage the "reports" approach to find other info, like collection or collection title or whatever.

Read comments for more info.

**Comment by arcadiafalcone** [comment]
Blocks #4326

**Comment by justinlittman** [comment]
* The slack link doesn't work.
* Can you give hints as to how this is supposed to happen?

**Comment by arcadiafalcone** [comment]
[only-barcodes-with-title.csv](https://github.com/sul-dlss/dor-services-app/files/10677237/only-barcodes-with-title.csv)

I was thinking to take the barcodes and use them to look up the corresponding catkey in Symphony, then add those catkeys to the identification metadata in the objects. This might be possible via Symphony reporting, but I'm not familiar enough with that to have more details.

**Comment by ndushay** [comment]
The code to get a ckey from a barcode is in `SymphonyReader.fetch_catkey`

**Comment by andrewjbtw** [comment]
Maybe I'm extra cautious but I think it would be good to check that the catkey retrieved from the barcode matches the existing title, just in case there was some data issue where a barcode was changed.

And since I suggested it, I am also willing to go through the list. I could do it from a report with: druid, barcode, ckey, title from Symphony, title currently in SDR

**Comment by peetucket** [comment]
I used the `SymphonyReader` class to lookup the catkeys for all barcodes attached, and then used the druid to lookup the SDR label in the cocina object.  The resulting report is attached here in this comment and includes the original columns, plus a `catkey` column and an `sdr_label` column.

There was one barcode which could not be found in symphony: `36105006174440` and thus no catkey was returned.

Question:
- In this report, I am outputing the `label` attribute of the cocina object instead of digging into the descriptive metadata in cocina.  I am not sure if this is producing the expected output.
- It's not clear to me if our `SymphonyReader` class gives us access to the title that is in symphony (don't think it does)
- I am not sure where the title supplied in the .csv file attached to this ticket came from

[only-barcodes-with-title_output.csv](https://github.com/sul-dlss/dor-services-app/files/10679361/only-barcodes-with-title_output.csv)

**Comment by andrewjbtw** [comment]
I got the title from solr to produce the CSV. I created that CSV with these steps:

- get all druids with catkey, barcode, title
- filter down to druids with only barcode

The Cocina label field could be wrong because it's a field Fedora generated once at registration and then could only be updated by XML editing. There are many divergences from title after subsequent updates.

**Comment by andrewjbtw** [comment]
I could also use just the catkey and get the title out of SW, assuming the records are public.

**Comment by peetucket** [comment]
Ahh....ok... so the cocina label field is probably useless then.  I could dig into the descriptive metadata if there is a canonical spot for the "main" title if that's helpful, or if you have a path with SW, that's fine too.  I can start working on the code to add the catkey to cocina while you do this (but hold off on actually running).

Do you know if we need to version/publish after the change, or just put into cocina and save?

**Comment by peetucket** [comment]
OK, updated report attached to this comment.  I replaced the "sdr_label" column with a title that is derived from cocina using the indexer code.  This should actually be an exact match to what you pulled from solr (basically 1==1).  But then I also hit the public Searchworks page, fetched a json, and parsed a title out of there, and added that as a column.  So that should be a confirmation (doesn't always match exactly, but hopefully close enough to verify it's the right object).

[only-barcodes-with-title_output.csv](https://github.com/sul-dlss/dor-services-app/files/10680537/only-barcodes-with-title_output.csv)

**Comment by andrewjbtw** [comment]
There's also a question of whether to refresh once the catkeys are added. I'll leave that up to @arcadiafalcone .

**Comment by peetucket** [comment]
Version each object.

**Comment by peetucket** [comment]
Ok, remediation complete with the following exceptions:

These objects could not have the catkey added because they throw a cocina validation error when editing:

- hc083jx5634
- ts082qm3256
- yn655rb4901

Example error seen here (when i tried to do one manually): https://app.honeybadger.io/projects/50568/faults/93474721

These objects had the catkey added but were not versioned because they were never fully accessioned:

- kz926yq3600
- mh416sv9340
- nm056wm4372
- nx386nc3743
- pf882hr9680
- qc397xv2617
- qf061yt7955
- qs226dk8042
- qz153bw7530
- rd269qj0014
- rk090gt4481
- rv199dh2176
- sn055wk3237
- ty336xs9628
- wb217fr6280
- wc110wb7190

This object's barcode returned no results from symphony:

- rd204pt4752

**Comment by ndushay** [comment]
@arcadiafalcone - just making sure you noticed Peter's last comment (I'm sure you did).  All followup is now handed off to you.

**Comment by arcadiafalcone** [comment]
Thanks - I'll take a look.
