### ISSUE TITLE
Research: Identifying location for objects with coordinate library MARC records

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4422]
*Provisional based on finalization of decision to include coordinate-specific locations in FOLIO holdings record*

When an 856 with second indicator 0 is present in a MARC record in FOLIO, an inventory holdings record is generated. Current plan is to include the coordinate library location (Law, Business, Hoover, but not Lane) in the holdings record for SDR objects. Therefore, when adding a new purl 856 to a FOLIO MARC record and generating a holdings record, it needs to be known whether the MARC record is associated with one of these three libraries. Would it be possible/feasible to add this location info to the object Cocina in Argo?

**Comment by justinlittman** [comment]
Do you have a sense about where in the Cocina this should go?

**Comment by lwrubel** [comment]
1. You probably only have the folio_instance_hrid, so you need to look up the instance ID (UUID) for the record, because that is needed to look up holdings for an instance: [^1]
`GET /inventory/instances?query=hrid==#{hrid}"`
In the JSON response, get `["id"]` from the first item in the ["instances"] array. (There should only be one item for an hrid.)

2. Use `GET /holdings-storage/holdings` to get the holdings for an instance ([API docs](https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/holdings-storage.html#holdings_storage_holdings_get)):
`/holdings-storage/holdings?query=instanceId=#{instance_id}`

I couldn't find an example to confirm this, but if there's no holding, the response probably has an empty `holdingsRecords` array and `'totalRecords': 0`.

3. Get the `holdingsRecords` array from the response. Each record has a `permanentLocationId`. 
Example holdings item in the `holdingsRecords` array:

```
{'id': 'edfd54d2-a196-5f6e-ae47-d451641f7fc5',
   '_version': 1,
   'hrid': 'ah13412279_3',
   'holdingsTypeId': '996f93e2-5b5e-4cf2-9168-33ced1f95eed',
   'formerIds': ['a13412279'],
   'instanceId': 'e43be071-1444-53e5-9894-ed9bed97a34f',
   'permanentLocationId': '1b14e21c-8d47-45c7-bc49-456a0086422b',
   'effectiveLocationId': '1b14e21c-8d47-45c7-bc49-456a0086422b',
   'electronicAccess': [],
   'administrativeNotes': [],
   'notes': [],
   'holdingsStatements': [],
   'holdingsStatementsForIndexes': [],
   'holdingsStatementsForSupplements': [],
   'statisticalCodeIds': [],
   'holdingsItems': [],
   'bareHoldingsItems': [],
   'metadata': {'createdDate': '2023-02-14T03:13:22.541+00:00',
    'createdByUserId': '3e2ed889-52f2-45ce-8a30-8767266f07d2',
    'updatedDate': '2023-02-14T03:13:22.541+00:00',
    'updatedByUserId': '3e2ed889-52f2-45ce-8a30-8767266f07d2'},
   'sourceId': 'f32d531e-df79-46b3-8932-cdd35f7a2264'}
```

4. We need to find out what the "code" is for each holding's permanentLocationId (e.g. SUL-SDR, EAR-LOCKED-MAPS). Look up a permanent location using `GET /locations/#{permanent_loc_id}. ((API Docs)[https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/location.html#locations__id__get)`
Example response:
{'locations': [{'id': '1b14e21c-8d47-45c7-bc49-456a0086422b',
   'name': 'SUL SDR',
   'code': 'SUL-SDR',
   'discoveryDisplayName': 'SUL SDR',
   'isActive': True,
   'institutionId': '8d433cdd-4e8f-4dc1-aa24-8a4ddb7dc929',
   'campusId': 'c365047a-51f2-45ce-8601-e421ca3615c5',
   'libraryId': 'c1a86906-ced0-46cb-8f5b-8cef542bdd00',
   'primaryServicePoint': '7c5abc9f-f3d7-4856-b8d7-6712462ca007',
   'servicePointIds': ['7c5abc9f-f3d7-4856-b8d7-6712462ca007'],
   'servicePoints': [],
   'metadata': {'createdDate': '2023-02-08T23:38:05.776+00:00',
    'createdByUserId': '7dc1ae38-1e06-4de9-ac86-568b9a2318ec',
    'updatedDate': '2023-02-08T23:38:05.776+00:00',
    'updatedByUserId': '7dc1ae38-1e06-4de9-ac86-568b9a2318ec'}}],
 'totalRecords': 1}


[^1]: @jermnelson and @shelleydoljack are checking whether our app user could have permissions for inventory-view so we could try: `/inventory-view/instance-set?limit=1&holdingsRecords=true&query=hrid=={hrid}"`. Will update if that looks like it will work for this scenario.

**Comment by arcadiafalcone** [comment]
Current 856 processing with Symphony (from https://docs.google.com/document/d/1sNZCgiYRwRgxyb_mWioDWoIs_kW0K0Mmm3CzvTueUYg/edit#):

Parse each line
  Captures ckey, druid, and 856
  If 856 exists, 
       Write to the delete file: any existing 856 for this druid on this ckey 
       Write to the merge file: the 856 for this druid for this ckey
  If 856 does not exist
       Write to the delete file: any existing 856 for this druid on this ckey

Call Symphony API to delete the 856s in the delete file
Call Symphony API to add the 856s in the merge file 

(So, “updates” are not done for an existing 856, but rather a delete of an existing 856 for that druid, and then an add of the incoming 856 for that druid)

Send delete and load reports to specific users

**Comment by lwrubel** [comment]
Closed since ticketed for FolioWriter
