### ISSUE TITLE
Report: virtual object constituents with catkeys

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4446]
To help answer some questions about 856 requirements for virtual object constituents, I would like a report of all virtual object constituents that are associated with catkeys.

Argo has a facet for virtual objects, so we can see a list of all virtual objects with this link: https://argo.stanford.edu/catalog?all=true&f%5Bhas_constituents_ssim%5D%5B%5D=has_constituents

Constituents of virtual objects are not faceted, unfortunately, hence the request for a report. It may also be desirable to add a facet for constituents, in which case I could then combine facets to identify all constituents with catkeys. I can ticket that separately.

**Comment by jmartin-sul** [comment]
looks like 5633 constituent druids have catkeys.  report attached as CSV, one line per druid/catkey combo.  if a constituent druid has multiple catkeys, it'll appear multiple times, though from eyeballing the results, it appears that the constituents with catkeys each have only one catkey (i didn't do any programmatic analysis on that front to be 100% sure).

i'm currently running a report that gets lists all constituent druids with all their parent druids, catkey or not, in case that's helpful for navigating the catkey results (and since that doesn't seem to be super easy to discover via the argo UI).  i'll attach that when it finishes.
[constituent_druids_with_catkeys_2023-03-22T15:33-07:00.csv](https://github.com/sul-dlss/dor-services-app/files/11045355/constituent_druids_with_catkeys_2023-03-22T15.33-07.00.csv)

@andrewjbtw

**Comment by jmartin-sul** [comment]
all constituent druids, and their parent virtual object druids, attached
[constituent_druids_parents_2023-03-22T16:00-07:00.csv](https://github.com/sul-dlss/dor-services-app/files/11045466/constituent_druids_parents_2023-03-22T16.00-07.00.csv)

**Comment by andrewjbtw** [comment]
Thanks!
