### ISSUE TITLE
Write a report for remediating scanned maps

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor-services-app#4702]
After verifying the validator...

In order to prepare for GIS remediation we need to have a report of all scanned maps. These objects 
(https://argo.stanford.edu/view/druid:bb051ch9980 have a subject value of `map coordinates` with coordinate data. The remediation will happen by collection, so the output of the report must include the collection druid and the object druid.

**Comment by peetucket** [comment]
Report results (it's big ... 119,145 items of which I spot checked a few)


[map_druids.csv](https://github.com/sul-dlss/dor-services-app/files/14502516/map_druids.csv)

**Comment by lwrubel** [comment]
Oops, I missed you already picked this up, @peetucket. Since we were running into issues with the `bin/validate-cocina.csv` script, I also ran a report on each environment, grabbing the map coordinates value as well. Interesting that some have more than one set of coordinates. Is that expected, @kimdurante and @thatbudakguy? 

[SubjectMapCoordinatesStage.csv](https://github.com/sul-dlss/dor-services-app/files/14511209/SubjectMapCoordinatesStage.csv)
[SubjectMapCoordinatesQA.csv](https://github.com/sul-dlss/dor-services-app/files/14511211/SubjectMapCoordinatesQA.csv)
[SubjectMapCoordinatesProd.csv](https://github.com/sul-dlss/dor-services-app/files/14511210/SubjectMapCoordinatesProd.csv)
