### ISSUE TITLE
Return a 422 if release tags are being requested for an APO

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/dor-services-app#4767]
Return a 422 if release tags are being requested for an AdminPolicy. Only collections and DROs have releaseTags.

**Comment by mjgiarlo** [comment]
@lwrubel @justinlittman What would y'all think about discussing this after stand-up? 400 implies to me that there's something wrong with the request syntactically, or that the request is otherwise malformed. Alternatives we could consider:

* HTTP 422: `... the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions`
* HTTP 200, and return an empty list if the object has no release tags (small tweak to https://github.com/sul-dlss/dor-services-app/blob/main/app/services/release_tags.rb#L73)

**Comment by justinlittman** [comment]
Discussed and decided to go with a 422.
