### ISSUE TITLE
Report request: cocina JSON for all google books druids

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4782]
I would like a copy of the full Cocina JSON for all the google books druids. The list of druids is long so I've attached it to this issue as a zip
[all-gbooks-solr-2024-04-02.zip](https://github.com/sul-dlss/dor-services-app/files/14843278/all-gbooks-solr-2024-04-02.zip)

I would like the output to be one gzipped file with a single JSON line per druid, the same output as the Argo bulk action to export Cocina. 

We shouldn't upload the result to github, so we'll need to work out where to put it. I could download it from a server or we could put it on google drive.

**Comment by andrewjbtw** [comment]
Instead of using the list of 3 million druids, it might be simpler to get the cocina for all items connected to the Google Books APO: druid:bf569gy6501 

Either way would work for me.

**Comment by jmartin-sul** [comment]
i wrote the code for this in the pattern we use for other reports in DSA, and i gave it a few niceties so that it's easily reusable.  i went with the approach of just using the provided list.  it was easy enough to `scp` it to a DSA VM, and taking a list seemed more reusable than hardcoding a query (and safer/easier than taking an arbitrary query -- easy enough to run a query, dump the druid list to a file, and feed that file to the reporting code).

it's running now on DSA, but i don't think there's space to hold the output: my rough estimate is that each druid is about 12.3 kB of cocina text (extrapolating from a 134 MB file with 10888 druid lines when i was trying to figure out the ETA for completion).  however, the DSA VM i'm on only has 6.3 GB of available space in its home directory, which is where i was putting the output.  `/tmp` only has 3.8 GB.

so, i think we're going to have to find a place to run this (as an aside, i first tried doing this on the sdr-infra VM, which has a read-only DB connection for prod data, since that felt safer, but i ran into issues with the default encoding on that VM making the output difficult to work with).

those 10888 druids took 15 minutes to get, including a 0.05 second pause between retrievals to help keep us from DoSing ourselves.  so my rough calculation there is that the report will take about 75 hours to run, which is hopefully tolerable?

**Comment by jmartin-sul** [comment]
i killed the report i was running that seemed like it'd overrun the available space, will bring up for discussion at standup

**Comment by jmartin-sul** [comment]
space problem figured out:
* on @andrewjbtw suggestion, i'm sending output to a shared mount that has many TB of free space
* on @justinlittman's suggestion, i reworked the report code to send only/all the report output to stdout, so that the output can be piped directly to `gzip` and then redirected to a file.  status/progress/etc info now goes to only the log file.  this approach does save a great deal of space.

i also took out the pause between cocina retrievals on justin's suggestion, and that doesn't seem to have caused any trouble (CPU and memory usage look fine while report is running, according to htop, and no errors reported to honeybadger).

now, based on checking in at the 10 minute and the 7 hour marks (from kicking off the report last night), it's looking roughly like:
* the report should take up about 1266 kB per record, leading to a `gzip`ed output file that runs just over 3 GB, instead of just over 34 GB of raw .jsonl with the original approach.
* the report should complete after roughly 33 hours, instead of 75ish hours (this is likely more due to the removal of a pause between retrievals than it is to streaming stdout to gzip instead of sending output to a file, though hard to say exactly since both changes were made at the same time).

will send @andrewjbtw the path to the output when the report has finished.

**Comment by jmartin-sul** [comment]
@andrewjbtw the report completed late friday night (well, sat morning, technically), and is available at `/dor/staging/suntzu/all-gbooks-solr-2024-04-02.cocina.2024-04-05T01:15:54-07:00.jsonl.gz`

it took just under 24 hours to complete (apr 5 01:15 to apr 6 00:44), and the final gzipped version of the report clcoked in at about 3.3 GB.

as a quick sanity check, i did `zcat /dor/staging/suntzu/all-gbooks-solr-2024-04-02.cocina.2024-04-05T01\:15\:54-07\:00.jsonl.gz | wc -l` and the result (2992479) matched the number of lines in the input file.

**Comment by justinlittman** [comment]
I really liked this solution @jmartin-sul!

**Comment by jmartin-sul** [comment]
> I really liked this solution @jmartin-sul!

thanks @justinlittman!  likewise, i really appreciated the suggestion to report to stdout and pipe to gzip.  that made for a huge space savings.
