### ISSUE TITLE
[ÜBER] Test the migration from F3 to the COCINA data model

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#748]
We want to run existing Fedora objects through the COCINA mapper to see where any gaps are.

# Questions & Answers

## How to run the migration?

Run it locally for now. May require a client cert to make connections to production Fedora.

## How to chunk up/sequence the data (by object/content type, by collection, by APO, by druid alpha, by registration date, by tag)?

Noting that web archives, ETDs, GIS, and other objects are different than others. First approach is get all druids and process them in whatever order. See "What's the simplest thing we can do" below. For future runs, we think we can use the Argo index to find subsets of druids.

## How can we do this work without taxing current systems?

We're not concerned about that at this time, since we'll either read druids from the Fedora RDBMS or Solr, and we'll do work locally.

## How to find/identify problematic gaps?

Missing source IDs for some objects.
... anything else that raises errors

## Do we store the mapped data for further analysis?

This seems useful to store, yes. Upload to private folder in Stanford Box for others to view?

## How to get lists of PIDs? 

Either pull from the Argo index or run a script on sul-dor-prod that hits MySQL underlying Fedora.

## What's the simplest thing we can do?

1. Spit out a list of PIDs.
2. For each PID, run the "show" DSA endpoint against the Fedora object. Record successes and failures to be able to calculate success rate and iterate on failures.

**Comment by jmartin-sul** [comment]
just starting in on this, but happy to pair if anyone's interested in joining the testing fun

**Comment by jmartin-sul** [comment]
i spun up a repo for this here:  https://github.com/sul-dlss/cocina-food-inspector

will keep improving this and will also create some tickets tomorrow.  i'll also test running this from my burndown box, to which i've granted the infra team access (login as `dor@dlss-dev-suntzu`), so that others can pick this up if they want while i'm off for a couple days.  also because this will involve lung running retrieval work, and i don't want to have to leave my laptop open and be at the mercy of my home internet connection, running it from the burndown box will be nice even without the benefit of a shared deployment.

the repo linked above could already be used for the "simplest thing" suggestion at the end of this issue's description, by tying together the two HOWTO sections to iterate over a druid list.  but better logging, job coordination, known druid tracking, etc would be nice too.

eventually would be nice to shape up into more of a real app with cap deployment, real ties to shared_configs, maybe a real database, etc.

**Comment by ndushay** [comment]
I myself am fond of lung running retrieval work.

**Comment by ndushay** [comment]
i wonder if we want a VM for this.

**Comment by mjgiarlo** [comment]
@ndushay :speech_balloon: 
> i wonder if we want a VM for this.

I believe @jmartin-sul already got one set up: `dor@dlss-dev-suntzu`

**Comment by jmartin-sul** [comment]
@mjgiarlo 💬 
> @ndushay 💬
> 
> > i wonder if we want a VM for this.
> 
> I believe @jmartin-sul already got one set up: `dor@dlss-dev-suntzu`

yeah, i also made a quick [braindump issue](https://github.com/sul-dlss/cocina-food-inspector/issues/1) from my notes last night, which addresses that in a bit more detail:  "would be nice to make this more of a real app. deploy to real VM, use shared configs for real, use PG instead of sqlite, sidekiq instead of delayed_job"

i'll file some better tickets from whatever seems worth keeping from that list, and then close that catchall issue.

i think this is the first time i've used my burndown box, but it definitely feels very handy here.  for at least this very manual scripty thing, it feels convenient to have a shared persistent place to run it, since the initial kernel of it is pretty straight-forward, and it's nice to not have to wait for VMs to be provisioned to get started with writing/testing/deploying it.  we'll see how that last part goes -- i'm still running locally 😄 (🤞 no big surprises on the VM).

**Comment by jmartin-sul** [comment]
update:
* have successfully deployed cocina-food-inspector to `dlss-dev-suntzu`
* loaded up a recent Fedora druid dump (exported yesterday) to its sqlite DB (it ran overnight, took about 5.5 hrs based on my glance at the logs, since i started loading the file just before midnight iirc, and it finished just after 5:30 am)
* started hitting dor-services-app prod's `/v1/objects/:druid` endpoint for druids we hadn't yet tried to retrieve on this prod instance.  did a batch of 5, then a batch of 50, a batch of 5000 is currently in progress.  so far way more successes than failures 🎉 

i didn't get a chance to file more granular issues from https://github.com/sul-dlss/cocina-food-inspector/issues/1 but i did at least get a lot of those things checked off (and added some new ones).  if this thing is on the right track and is used by multiple people, i think we will want some of the "would be nice to make this more of a real app" ideas in that ticket.  in particular, a real DB, and some level of unit testing so we can iterate on it more comfortably.  i'm already feeling like i'm doing too much manual testing for the code changes i've made.  on that note, probably also time to start doing PR review (i've just been pushing to master to get it going).

there's documentation in the README for how to use the test harness app on prod:  https://github.com/sul-dlss/cocina-food-inspector#use-this-project-on-the-shared-deployment-environment-aka-how-to-run-this-on-johns-burndown-box

that section cuts to the chase, but it might be helpful to read the whole thing.  there's not a ton there, though it's very much the sort of off the cuff "here's a bunch of examples" style that i'm not so fond of.  just tried to keep usable accurate notes as i was going in case someone wanted to run with this while before i'm back from staycationing (though i'd also be happy to pair for 30 min or so this afternoon or tomorrow if that might help).

questions:
* do we want to add https://github.com/sul-dlss/cocina-food-inspector/ to the current and/or next work cycle zen hub board?
* is the jokey name of the repo usable/sensible?  or should we change it so people aren't constantly forgetting what to look for?  i usually try to resist the silly name temptation nowadays, but the best buttoned down name i could think of was "cocina-mapper-test-harness", which felt a little off to me (the code might end up being more or less comprehensive than that, so that name feels too specific, and it's still a little verbally unwieldy).

**Comment by jmartin-sul** [comment]
also if you do anything with this, heed the advice to use a screen session.

and i get the impression that sqlite is not the most multi-user amenable DB, so probably look to see whether someone else has an active screen session or a rails console when you log onto the VM.  so yeah, maybe it would be nice to use more of a real DB.

**Comment by ndushay** [comment]
@mjgiarlo you probably came after we were being empowered to use puppet by having burn-down boxes to test puppety stuff.   The VM John is using now is his burn-down box.  This is not the right box for this work.

**Comment by mjgiarlo** [comment]
@ndushay :speech_balloon: 
> @mjgiarlo you probably came after we were being empowered to use puppet by having burn-down boxes to test puppety stuff. The VM John is using now is his burn-down box. This is not the right box for this work.

OK, can you say why not?

**Comment by ndushay** [comment]
1.  it's not named for what we're using it for;  ops would have no idea it was used for anything.
2.  those boxes are generally not well resourced with ram, or log rotation or anything like that

probably other reasons as well.
I let them delete my burndown box.

**Comment by mjgiarlo** [comment]
> 1. it's not named for what we're using it for;  ops would have no idea it was used for anything.
> 2. those boxes are generally not well resourced with ram, or log rotation or anything like that
> 
> probably other reasons as well.
> I let them delete my burndown box.

Ah, OK. Given the issue description above didn't specify we needed a VM/server for this, I figured *anywhere* would be a fine place to do the work. I don't have strong opinions about where this happens so either is fine by me.

**Comment by ndushay** [comment]
I've been hearing that we're going to need to do this over and over, so 🤷‍♀

**Comment by mjgiarlo** [comment]
@ndushay 
> I've been hearing that we're going to need to do this over and over, so

:+1:

**Comment by jcoyne** [comment]
Possibly superseded by #1084

**Comment by jmartin-sul** [comment]
> Possibly superseded by #1084

seems likely, closing this.

**Comment by jmartin-sul** [comment]
deprecated the repo i spun up since this approach has been superseded: https://github.com/sul-dlss-deprecated/cocina-food-inspector
