### ISSUE TITLE
Validate that contentMetadata shelve and publish attributes are set correctly for dark objects

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#767]
Dark objects must have shelve and publish set to false for all files.  Fail the publish and shelve step if this is not true.

**Comment by ndushay** [comment]
Is this done?  I see PR #769 and #788

Or is it waiting for https://github.com/sul-dlss/pre-assembly/pull/645 to be merged and deployed so PR #788 can be reversed?

Another question might be ... why are we doing this in dor-services-app ?   We don't do it for other types of objects ...

**Comment by ndushay** [comment]
PR sul-dlss/pre-assembly#645 has been merged and deployed, so should PR #788 be reversed?

I still have this question: why are we doing this validation, and why here, in dor-services-app ? We don't do it for other types of access rights.

**Comment by jcoyne** [comment]
@ndushay I think you're absolutely right that this is the wrong place for this, however, as many pathways just put data on the `/dor` mount and initiate a workflow, there's no good place where data is validated and I believe Andrew or Peter suggested here.  As we move to a API based architecture, validation issues could be caught early, however this would require us to (at a minimum):
- add an update capability to SDR-API (which in turn depends on a mapping for descMetadata MODS to cocina, which isn't done yet)
- Convince/train everyone to use the sdr-client rather than pre-assembly.

**Comment by justinlittman** [comment]
Looking at the comments in the code, WAS also needs to be fixed. See https://github.com/sul-dlss/was_robot_suite/issues/209
