### ISSUE TITLE
Should source_id be a required field?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#852]
If so, why?

**Comment by andrewjbtw** [comment]
We've had this conversation a few times and it seems like there are a few different ways source_id could and could not be required, depending on what part of the SDR system you're looking at. 

The key places as I see it are:

1. At registration
2. On the registration form
3. In the cocina model

In practice, source_id has been required on the registration form. It has not been required for registration in general. I haven't been able to figure out whether it is or is not required for Cocina.

**What is a source_id?**

A large proportion of what's deposited in SDR, historically and currently, are representations of objects that are also represented in other systems. Digitized paper and A/V collections have physical manifestations, and those physical objects are managed in systems that have their own identifiers. Books have barcodes, archival materials have collection numbers and physical locations, etc. Ideally, everything has some unique identifier, or some way of generating a unique identifier.

When someone deposits into the SDR, at least from within the library, they should provide that unique identifier as the source_id. That way you can tell 

- if an item has been deposited before
- where to look for the original item if you're looking at its SDR representation (i.e. where can I find the original, or more information about the original?)

No other metadata in an SDR object serves this function. You cannot use title because titles are not unique. 

**What if there's no original source identifier?**

Self-deposits and certain types of electronic "born-digital" materials have not been deposited with meaningful source_ids. The now-retired EEMS (Everyday Electronic Materials) did not use source_ids for deposits of electronic documents like government documents and electronic serials. Items deposited in Hydrus get an arbitrary source_id that is generated by the system and has nothing to do with originals.

You could make the theoretical argument that for certain materials the SDR object is the original object and the druid is essentially the same as the source_id. There's also a practical argument that you can't expect external users to provide a source_id. I think that's why Hydrus assigns a source_id in the background and it's basically invisible to users.

**What if there is an original source identifier, but it wasn't provided?**

The SDR did not always require source_id. It seems to have been made a requirement around 2012-2013. The result is that there are a few thousand items without one that almost all date back to that time. Our current approach is to try to remediate them by assigning source_id after the fact. The data that would have been used to create these source_ids generally exists because it comes from the systems used to manage the original materials, which still exist.

**Should source_id be required?**

Given the above, I think:

- it fills a need that isn't filled by any other field
- it is meaningful for the vast majority of content deposited from within SUL
- it can be auto-generated for material where source_id isn't meaningful or it isn't practical to ask depositors to generate one

So requiring at:

- registration - I would say yes, but there are cases where it can be safely auto-generated
- Argo registration form - I would say yes because this is a staff user interaction
- cocina - I would say ideally, but we have legacy data to work around

**Comment by ndushay** [comment]
to close this ticket:

move appropriate documention either to cocina-models code where source-id is used and/or NOT checked, OR to cocina-models wiki.

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/cocina-models/pull/122
