### ISSUE TITLE
ensure CocinaMapper maps all descMd (needed by ETD)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#952]
requires PRs sul-dlss/cocina-models/pull/126 and sul-dlss-labs/cocina-descriptive-metadata/pull/2 before merging, but the work can be started immediately.

We need the ObjectsController.show method to return a populated cocina model that has fully populated descriptive metadata fields.

I believe if you follow the call chain, the actual mappings done thus far are minimal, and are here:  https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/from_fedora/descriptive.rb

Arcadia has created all the appropriate attributes in cocina models, and the mappings are here https://github.com/sul-dlss-labs/cocina-descriptive-metadata ( https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/2 unless it's already merged - examples provided )

~~Examples of mapped etds:  https://github.com/sul-dlss/cocina-models/tree/description_v4/spec/fixtures/description~~ these are older and probably not quite correct.

For mapping completeness/correctness, we may want @arcadiafalcone to sign off on the PR for this.

**Comment by aaron-collier** [comment]
As I'm wrapping up this PR, Some questions (likely specifically for @arcadiafalcone):

I'm basing my current PR mostly on the the example at: https://github.com/sul-dlss/cocina-models/blob/master/spec/fixtures/description/etd2.json and the current argo data stream which I've stored: https://gist.github.com/aaron-collier/377ef0c4c8501f46a70c1acf876b677b

Questions:

1. Contributor:
    1. Author role code (i.e. 'aut') is not in the data. Should this be generated during mapping? If so, are there other new codes that may need mapping?
    2. Role URI and role source URI do not exist in the current data. It looks like they can be generated during mapping if the expectation is they will always be `http://id.loc.gov/....
    3. In the cocina-models example, author is duplicated with a source related to `Elements`, is there more info.on this?
    4. Degree supervisor: the code value in cocina is `dgs` but in argo it is `ths`. Should this be translated?
2.Events. I don't see anything about events in the current data. What will the source for this information be?
3. Form: 
    1. Same as above, the URI and source.uri values are not in the current argo data but look generate-able... what is the expectation here?
4. Language:
    1. In the example record, only the code, e.g. `eng` and the source.code, e.g. `iso239-2b` are in the current data, should the URI and source.uri be generated?
5. Note:
    1. The cocina example has addition values and types that are not in the current record as well as a `thesis` type with a `structuredValue` attribute, what is the expectation for this data?
6. Additional data blocks that need clarifcation are `identifier`, `marcEncodedData`, and `adminMetadata`.


Disclaimer: If any. of the questions above are confusing or need clarification, I'm happy to discuss, these are certainly from a less-than-informed and new-ish to cocina place.

Thank you :-)

**Comment by arcadiafalcone** [comment]
Below `properties/` and `readers/` refer to elements in those datastreams in Argo, which derive from the raw data provided by the ETD deposit app.

1. Contributor
i. The role data is generated during mapping. Current local practice is to use marcrelator roles in MODS and RDA Agent (the `Elements` URI) properties for the same kind of data in MARC. The cocina descriptive model is meant to be able to generate both MODS and MARC without having to do mapping work in the code, which is why both are present in the cocina record. `aut` and `author` (and the associated authority info) are assigned to the name in `properties/name`. `dgs` and `degree supervisor` are assigned to the name in `readers/reader/name` with `readerrole` = "Advisor," "Dissertation Co-Advisor," or "Co-Adv."  (This role term is a change from current practice that has been approved by the Metadata Department.) `ths` and `degree committee member` are assigned to other values of `readers/reader/name`. These are the only role codes that need to be accommodated.
ii. The `source` info should be generated along with the `role`, and will always be the same for each role.
iii. See above - it's two different vocabularies both in use locally.
iv. See above - this is an intentional change.

2a. Events
i. 
`thesis submission`: The event date value is derived from `properties/submit_date`, converted to w3cdtf.  The school and/or department values under `contributor` are derived from `properties/schoolname` and `properties/department` according to this logic: https://github.com/sul-dlss/hydra_etd/blob/94a3dbfe87648d8471501b7725bbeef586358757/app/services/stub_marc_record_creator.rb#L143. All other data in the example is static and can be generated as-is for each record.
`degree conferral`: The event date value is taken from `properties/degreeconfyr`. The degree type note value is derived from `properties/degree` according to this logic: https://github.com/sul-dlss/hydra_etd/blob/42a404b0b7b7fd4ab4e2a8e940eb9e23ad18b820/app/helpers/etds_helper.rb#L42. All other data in the example is static and can be generated as-is for each record.
`publication`: The event date value is the current year at the point of first generating the record. All other data in the example is static and can be generated as-is for each record.
`copyright`: The copyright date value is derived from `properties/submit_date`, converted to w3cdtf. If the `submit_date` is not present, use the value in `properties/degreeconfyr`.

2b. Form
i. Everything in `form` is static data and can be generated for each record based on the example.

3. Language
i. The other data is static and should be generated.

4. Note
"Submitted to X": The value should be generated from `properties/schoolname` and `properties/department` according to the logic at https://github.com/sul-dlss/hydra_etd/blob/94a3dbfe87648d8471501b7725bbeef586358757/app/services/stub_marc_record_creator.rb#L108.
`thesis`: The values in structuredValue should be generated according to the logic at https://github.com/sul-dlss/hydra_etd/blob/94a3dbfe87648d8471501b7725bbeef586358757/app/services/stub_marc_record_creator.rb#L116.
`statement of responsibility`: The value should be generated from `properties/name`, `properties/prefix`, `properties/suffix`, and `properties/title` according to the logic at https://github.com/sul-dlss/hydra_etd/blob/94a3dbfe87648d8471501b7725bbeef586358757/app/services/stub_marc_record_creator.rb#L160 and https://github.com/sul-dlss/hydra_etd/blob/94a3dbfe87648d8471501b7725bbeef586358757/app/services/stub_marc_record_creator.rb#L221.

5a. Identifier
i. The `ETD ID` is from `properties/dissertation_id`.

5b. MARC encoded data
i. This is static except for the dates in the 008, which are generated according to the logic at https://github.com/sul-dlss/hydra_etd/blob/94a3dbfe87648d8471501b7725bbeef586358757/app/services/stub_marc_record_creator.rb#L45. (Since we already have a mapping, it makes more sense to directly generate this data in order to be able to generate MARC from cocina, rather than trying to map each code to its own cocina field and back again, especially as much of this info is already represented elsewhere in the record in another form.)

5c. Admin metadata
i. This is static except for creation date, which refers to the date the record was created, and so should insert the current date at the time the cocina record is generated.

**Comment by aaron-collier** [comment]
Thank you @arcadiafalcone , just catching up post-vacation and will follow up as necessary.
